ceph_cluster: ceph
ceph_conf_file: "/etc/ceph/ceph.conf"

mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws

rgw_pcs_resource: p_ceph_rgw

ceph_common_packages:
  - ceph
  - ceph-common
  - ceph-deploy
  - libcephfs1
  - python-ceph-compat
  - python-cephfs

ceph_lib_packages:
  - librados2
  - librbd1
  - python-rados
  - python-rbd

ceph_rgw_packages:
  - ceph-radosgw

keystone_accepted_roles: "Member, _member_, admin, SwiftOperator"
keystone_token_cache_size: "500"
keystone_revocation_interval: "500"
rgw_s3_use_keystone: "true"

ceph_conf:
  - section: "global"
    configurations:
      - option: "rgw keystone url"
        value: "http://{{ management_vip }}:{{ keystone_admin_port }}"
        apply_to:
          - "{{ rgw_group_name|default('rgw') }}"
      - option: "rgw keystone admin token"
        value: "{{ keystone['admin_token'] }}"
        apply_to:
          - "{{ rgw_group_name|default('rgw') }}"
      - option: "rgw keystone accepted roles"
        value: "Member, _member_, admin, SwiftOperator"
        apply_to:
          - "{{ rgw_group_name|default('rgw') }}"
      - option: "rgw keystone token cache size"
        value: "{{ keystone_token_cache_size }}"
        apply_to:
          - "{{ rgw_group_name|default('rgw') }}"
      - option: "rgw keystone revocation interval"
        value: "{{ keystone_revocation_interval }}"
        apply_to:
          - "{{ rgw_group_name|default('rgw') }}"
      - option: "rgw s3 auth use keystone"
        value: "{{ rgw_s3_use_keystone }}"
        apply_to:
          - "{{ rgw_group_name|default('rgw') }}"
