---
- set_fact:
    selected_packages: "{{ ceph_common_packages|union(ceph_lib_packages)|join(' ') }}"

- set_fact:
    selected_packages: "{{ ceph_common_packages|union(ceph_lib_packages)|union(ceph_rgw_packages)|join(' ') }}"
  when: inventory_hostname in groups[rgw_group_name]

- name: downgrade packages
  shell: "yum downgrade -y {{ selected_packages }}"

- set_fact:
    ceph_downgraded: true
