---
- name: install ceph common packages
  yum:
    name: "{{ item }}"
    state: "{{ (downgrade_ceph|default('false')|bool) | ternary('present', 'latest') }}"
    update_cache: "{{ (downgrade_ceph|default('false')|bool) | ternary('no', 'yes') }}"
  with_items: "{{ ceph_common_packages }}"
  register: install_ceph_common

- name: install ceph library packages
  yum:
    name: "{{ item }}"
    state: "{{ (downgrade_ceph|default('false')|bool) | ternary('present', 'latest') }}"
    update_cache: "{{ (downgrade_ceph|default('false')|bool) | ternary('no', 'yes') }}"
  with_items: "{{ ceph_lib_packages }}"
  register: install_ceph_lib

- name: install ceph rados gateway
  yum:
    name: "{{ item }}"
    state: "{{ (downgrade_ceph|default('false')|bool) | ternary('present', 'latest') }}"
    update_cache: "{{ (downgrade_ceph|default('false')|bool) | ternary('no', 'yes') }}"
  with_items: "{{ ceph_rgw_packages }}"
  when: (groups[rgw_group_name] is defined
         and inventory_hostname in groups[rgw_group_name])
  register: install_ceph_radosgw

- set_fact:
    ceph_common_upgraded: true
  when: install_ceph_common.changed

- set_fact:
    ceph_lib_upgraded: true
  when: install_ceph_lib.changed

- set_fact:
    ceph_radosgw_upgraded: true
  when: install_ceph_radosgw.changed

- name: reload ceph systemd services
  shell: "systemctl daemon-reload"
  when: install_ceph_common.changed or
        install_ceph_radosgw.changed or
        (ceph_downgraded|default('false')|bool)
