---
- include: config.yml

- include: downgrade_packages.yml
  when: (downgrade_ceph|default('false')|bool)

- include: install_packages.yml
  when: action == 'install_packages'

- include: restart_mons.yml
  when:
    - action == 'restart_mons'
    - (ceph_common_upgraded|default('false')|bool) or
      (ceph_lib_upgraded|default('false')|bool) or
      (force_restart_ceph|default('false')|bool) or
      (ceph_downgraded|default('false')|bool)

- include: restart_osds.yml
  when:
    - action == 'restart_osds'
    - (ceph_common_upgraded|default('false')|bool) or
      (ceph_lib_upgraded|default('false')|bool) or
      (force_restart_ceph|default('false')|bool) or
      (ceph_downgraded|default('false')|bool)

- include: restart_rgws.yml
  when:
    - action == 'restart_rgws'
    - (ceph_common_upgraded|default('false')|bool) or
      (ceph_lib_upgraded|default('false')|bool) or
      (ceph_radosgw_upgraded|default('false')|bool) or
      (force_restart_ceph|default('false')|bool) or
      (ceph_downgraded|default('false')|bool)
