- name: set osd flags
  command: ceph osd set {{ item }} --cluster {{ ceph_cluster }}
  with_items:
    - noout
    - noscrub
    - nodeep-scrub
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: restart ceph osds
  shell: "/etc/init.d/ceph restart osd"
  changed_when: false

- name: waiting for clean pgs...
  shell: |
    test "$(ceph pg stat --cluster {{ ceph_cluster }} | tr , '\n'  | sed 's/^.*pgs: //' | awk '/active.clean/ { SUM += $1 } END {print SUM}')" -eq "$(ceph pg stat --cluster {{ ceph_cluster }}  | sed 's/pgs.*//;s/^.*://;s/ //')" && ceph health --cluster {{ ceph_cluster }}  | egrep -sq "HEALTH_OK|HEALTH_WARN"
  register: result
  until: result.rc == 0
  retries: "{{ health_osd_check_retries }}"
  delay: "{{ health_osd_check_delay }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"

- name: unset osd flags
  command: ceph osd unset {{ item }} --cluster {{ ceph_cluster }}
  with_items:
    - noout
    - noscrub
    - nodeep-scrub
  delegate_to: "{{ groups[mon_group_name][0] }}"
