---
- name: set mon_host_count
  set_fact: mon_host_count={{ groups[mon_group_name] | length }}

- debug: msg="WARNING - upgrading a ceph cluster with only one monitor node ({{ inventory_hostname }})"
  when: mon_host_count | int == 1

- name: restart ceph mons
  shell: "/etc/init.d/ceph restart mon"
  changed_when: false

- name: set mon_host_count
  set_fact: mon_host_count={{ groups[mon_group_name] | length }}

- name: select a running monitor if multiple monitors
  set_fact: mon_host={{ item }}
  with_items: "{{ groups[mon_group_name] }}"
  when:
    - mon_host_count | int > 1
    - item != inventory_hostname

- name: select first monitor if only one monitor
  set_fact: mon_host={{ item }}
  with_items: "{{ groups[mon_group_name][0] }}"
  when:
    - mon_host_count | int == 1

- name: waiting for the monitor to join the quorum...
  shell: |
    ceph -s --cluster {{ ceph_cluster }} | grep election | sed 's/.*quorum//' | egrep -sq {{ ansible_hostname }}
  register: result
  until: result.rc == 0
  retries: "{{ health_mon_check_retries }}"
  delay: "{{ health_mon_check_delay }}"
  delegate_to: "{{ mon_host }}"

