---
- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ pkg_install }}"

- name: Ensure docker service directory exists
  file:
    path=/etc/systemd/system/docker.service.d
    state=directory
    recurse=yes

- name: Configure docker service
  become: True
  template:
    src=docker_systemd_service.j2
    dest=/etc/systemd/system/docker.service.d/eayunstack.conf
  register: docker_systemd_conf

- name: Reload docker service file
  become: True
  command: systemctl daemon-reload
  when: docker_systemd_conf.changed

- name: Start docker
  service:
    name: docker
    state: started
  become: True

- name: Enable docker
  service:
    name: docker
    enabled: yes
  become: True

- name: Ensuring log directory exist
  file:
    path: "{{ eayunstack_log_base }}"
    state: "directory"
    owner: root

