---
- name: Copying over trove haproxy conf files
  template:
    src: "trove-api-haproxy.conf.j2"
    dest: "{{ haproxy_config_base }}/{{ trove_haproxy_order }}-trove-api.cfg"
  notify: Reload HAProxy
